name: Generate Isometric Commit Calendar

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install github-isometric-contribution-calendar
        run: npm install -g github-isometric-contribution-calendar

      - name: Generate Isometric Calendar
        run: |
          github-isometric-contribution-calendar
          mv ./out/isometric-calendar.svg ./isometric-calendar.svg

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add isometric-calendar.svg
          git commit -m 'Generate isometric calendar'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
